### PR TITLE
odr violation fixes

### PR DESCRIPTION
**Pull request by kuhar**
Added fixes for ODR violations (that resulted in linker errors) + minimalistic regression test.

§14.7.3/12:
`An explicit specialization of a function template is inline only if it is declared with the inline specifier or
defined as deleted, and independently of whether its function template is inline.`

I was not sure how you'd like to handle additional tests, so I've just added a simple cmake.

### CODE REVIEW

**Comment by jeaye** [comment]
You're absolutely right about the ODR issues; I've had this bite me a couple of times in jeayeson. Thanks for the PR. With that said, I really don't want to bring in a CMake dependency for the additional test (which is also very much appreciated). The current tests need to be separated into more binaries than just one, which is part of a test organization task I have planned. If you could either integrate your test into the current build system, or just remove the test (if you do this, I'll make an issue to ensure it's not forgotten), I'll happily merge this.

**Comment by jeaye** [comment]
After looking over the current Makefile again, it'd be a real hassle to cleanly integrate this. Let's drop the test, I'll make an issue, and we can merge the ODR fixes. Let me know how that sounds.

**Comment by kuhar** [comment]
I've removed the test.

**Comment by jeaye** [comment]
Thanks!

**Pull request merged**
